name: ecommerce_fraud_analysis
version: 1.0.0

profile: ecommerce_fraud_analysis

model-paths: ["models"]

models:
  ecommerce_fraud_analysis:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table